### ISSUE TITLE
SD-1000 can't working on SMS 

### ISSUE THREAD

**Issue by hpx1984** [aotta/SD-1000#1]
Hi Sir Aotta

i built one set and seems every thing is good (programing pico board and upload ROM all are success)
but it can't working on sega SMS console （both of sg-1000 or SMS ROM into the PICO board），my SMS console will auto run the original game 
please help to comment if any thing i can do?
many thanks your great project and help

**Comment by aotta** [comment]
The card is for sg-1000, sc-3000 and Mk-III only, SMS has a different pinout

**Comment by aotta** [comment]
Not an issue, project is not for SMS system

**Comment by hpx1984** [comment]
many thx your comment Sir Aotta
seems my friend provided wrong information to me , he said SG-1000 game card can use on SMS

**Comment by aotta** [comment]
I think it's possible on Japanese version of SMS, not the EU or US ones,
because of the different pinout.

Il giorno gio 13 giu 2024 alle ore 16:00 hpx1984 ***@***.***>
ha scritto:

**Comment by hpx1984** [comment]
Hi Sir Aotta
﻿
i think so too , i found some information ot he game card pin layout and seems some one already created the converter
i try to study it and try to build one ,but im not sure whether i can success 
https://www.smspower.org/forums/16811-ThanksToThisSiteFinallyMadeAWorkingMarkIIISMSConverter
